// Auto-generated code. Do not edit.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "myImage":return img`
.........ffffffffffffff.........
........fccccccccccccccf........
........8888888888888888........
........2222222222222222........
......ff8888888888888888ff......
......fcfccccccccccccccfcf......
......fcfcffffffffffffcfcf......
......fcfcbbbbbbbbbbbbcfcf......
......fcfcddddddddddddcfcf......
......fcfcccccfccfcccccfcf......
......fcfcccccfccfcccccfcf......
......fcfcccccfccfcccccfcf......
......fcfcccccfccfcccccfcf......
......fcfcccccfccfcccccfcf......
......fffccccffccffccccfff......
........fcccfcfccfcfcccf........
........fcccfccccccfcccf........
........fccccfccccfccccf........
........fcccccffffcccccf........
........fccccccccccccccf........
.........fccccccccccccf.........
..........fcccffffcccf..........
...........fccccccccf...........
.........ffcfccccccfcff.........
.......ff55ccffffffcc55ff.......
......fccc55cccccccc55cccf......
......fcccc55cccccc55ccccf......
.....fcccccc555cc555ccccccf.....
.....fcccccccc5555ccccccccf.....
....fccccccccccccccccccccccf....
....fccccccccccccccccccccccf....
....ffffffffffffffffffffffff....
`;
            case "image3":
            case "myImage1":return img`
. . . . . . . . . . . . . . . . 
. . . . . . f f f f . . . . . . 
. . . . . f 7 1 3 3 f . . . . . 
. . . . f 7 7 1 3 3 3 f . . . . 
. . . . f 7 7 1 3 3 3 f . . . . 
. . . f 7 7 1 1 3 3 1 1 f . . . 
. . . f 7 1 1 1 1 1 1 2 f . . . 
. . f 7 1 1 5 1 1 1 2 2 2 f . . 
. . f 1 1 5 5 5 1 2 2 2 2 f . . 
. . f 1 1 1 5 1 1 2 2 2 2 f . . 
. . f 4 4 1 1 1 1 1 2 2 2 f . . 
. . f 4 4 4 1 1 1 1 1 2 2 f . . 
. . f 4 4 4 4 1 1 a 1 1 1 f . . 
. . . f 4 4 4 1 a a a 1 f . . . 
. . . . f f 4 1 a a f f . . . . 
. . . . . . f f f f . . . . . . 
`;
            case "image4":
            case "myImage2":return img`
................................
................................
................................
................................
................................
..............fffff.............
.............ff111ff............
............ff1fff1ff...........
...........ff1fffff1ff..........
..........ff1fffafff1ff.........
..........f1fffffffff1f.........
.........ff1fffffffff1ff........
........ff1fff9fff9fff1ff.......
........f1fffffffffffff1f.......
.......ff1fffffffffffff1ff......
.......f1fff7fffffff7fff1f......
.......f1fffffffffffffff1f......
.......f1fffffff2fffffff1f......
.......f1fffffffffffffff1f......
.......f1fffffffffffffff1f......
.......f1fff5fffffff5fff1f......
.......f1fffffffffffffff1f......
.......f1fffffffafffffff1f......
.......ff11fffffffffff11ff......
........fff1fffffffff1fff.......
..........ff11fffff11ff.........
...........fff11111fff..........
.............fffffff............
................................
................................
................................
................................
`;
            case "image5":
            case "myImage3":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
..............ffff..............
.............f9999f.............
............f99aa99f............
...........f99aaaa99f...........
...........f9aa33aa9f...........
..........f99a3333a99f..........
..........f9aa3443aa9f..........
..........f9a334433a9f..........
.........f99a344443a99f.........
.........f9aa347743aa9f.........
.........f9a33477433a9f.........
.........f9a34477443a9f.........
.........f9a33444433a9f.........
.........f9aa334433aa9f.........
.........f99aa3333aa99f.........
..........f99aaaaaa99f..........
...........f99999999f...........
............ffffffff............
................................
................................
................................
................................
................................
`;
            case "image6":
            case "myImage4":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
..............ffff..............
.............f2222f.............
............f224422f............
............f244442f............
...........f22455422f...........
...........f24455442f...........
..........f2245555422f..........
..........f2445995442f..........
..........f2459119542f..........
..........f2445995442f..........
..........f2244554422f..........
...........f22444422f...........
............f222222f............
.............ffffff.............
................................
................................
................................
................................
................................
................................
`;
            case "image7":
            case "myImage5":return img`
................................
................................
................................
................................
................................
................................
................................
................................
.............fffffff............
...........ff5555555ff..........
..........f55555555555f.........
..........f55555555555f.........
.........f555f5555f5f55f........
.........f55fff5555f555f........
.........f555f5555f5f55f........
.........f5555555555555f........
.........f5555555555555f........
.........f5555555555555f........
.........f555f55555f555f........
..........f555fffff555f.........
..........f55555555555f.........
...........ff5555555ff..........
.............fffffff............
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;
            case "image2":
            case "myImage0":return img`
. . . . . . . . . . . . . . . . 
. . . . . . a a a a a . . . . . 
. . . . . . a 9 9 9 a a a . . . 
. . . . . . a a 9 2 9 9 a . . . 
. . . . . . . a 9 2 9 9 a . . . 
. . . . . . a a 9 2 9 a a . . . 
. . . . . a a 9 2 9 a a . . . . 
. . . . . a a 9 2 9 a . . . . . 
. . . . . . a a 9 2 9 a a . . . 
. . . . . . . a 9 2 9 9 a . . . 
. . . . . . . a 9 2 2 9 a . . . 
. . . . . . a a 9 2 9 a a . . . 
. . . . . a a 9 2 9 a . . . . . 
. . . . . a a 9 2 9 a a . . . . 
. . . . . . a a 9 2 9 a a . . . 
. . . . . . . a 9 2 9 9 a . . . 
`;
            case "image8":
            case "myImage6":return img`
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
................................
`;
            case "image9":
            case "myImage7":return img`
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
. . . . . . . . . . . . . . . . 
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "myAnim":
            case "anim1":return [img`
.........ffffffffffffff.........
........fccccccccccccccf........
........8888888888888888........
........2222222222222222........
......ff8888888888888888ff......
......fcfccccccccccccccfcf......
......fcfcffffffffffffcfcf......
......fcfcbbbbbbbbbbbbcfcf......
......fcfcddddddddddddcfcf......
......fcfcccccfccfcccccfcf......
......fcfcccccfccfcccccfcf......
......fcfcccccfccfcccccfcf......
......fcfcccccfccfcccccfcf......
......fcfcccccfccfcccccfcf......
......fffccccffccffccccfff......
........fcccfcfccfcfcccf........
........fcccfccccccfcccf........
........fccccfccccfccccf........
........fcccccffffcccccf........
........fccccccccccccccf........
.........fccccccccccccf.........
..........fcccffffcccf..........
...........fccccccccf...........
.........ffcfccccccfcff.........
.......ff55ccffffffcc55ff.......
......fccc55cccccccc55cccf......
......fcccc55cccccc55ccccf......
.....fcccccc555cc555ccccccf.....
.....fcccccccc5555ccccccccf.....
....fccccccccccccccccccccccf....
....fccccccccccccccccccccccf....
....ffffffffffffffffffffffff....
`, img`
.........ffffffffffffff.........
........fccccccccccccccf........
........8888888888888888........
........2222222222222222........
........88888888888ff888........
........fcccccccccfccfcf........
........fffffffffcfccfcf........
.........fbbbbbbbcfccfcf........
..........fddddddcfccfcf........
..........fcccccccfccfcf........
..........fcccccccfccfcf........
..........fcccccccfccfcf........
..........fcccccccfccfcf........
.........ffcccccccfccfcf........
........fccccfcccccffccf........
........fccccfcccccccccf........
.........fffffcccccccccf........
...........fcccccccccccf........
..........fccccccccccccf........
..........fccccccccccccf........
..........ffffccccccccff........
..........fccccccccccff.........
..........fccccccccffff.........
..........ffcccccffcc5ff........
...........ffffffccc555ff.......
............fccccc555cccff......
..........fffcc55555cccccff.....
.........ff5555555ccccccccf.....
........ff555cccccccccccccff....
.......ffccccccccccccccccccf....
.......fcccccccccccccccccccf....
.......fffffffffffffffffffff....
`, img`
.........ffffffffffffff.........
........fccccccccccccccf........
........8888888888888888........
........2222222222222222........
........8888888ff888888f........
........fcccccfccfcccccf........
........fcccccfccfcccccf........
.........fccccfccfcccccf........
..........fcccfccfcccccf........
..........fcccfccfcccccf........
.........ffcccfccfcccccf........
.........fccccfccfcccccf........
........ffccccfccfcccccf........
........fcccccfccfcccccf........
.......ffccccccffccccccf........
......fccccccccccccccccf........
......fcccfccccccccccccf........
.......fffcccccccccccccf........
.........fccccccccccccff........
........ffcccccccccccff.........
........fcccccccccccff..........
........fffccccccccff...........
........fccccccccffffff.........
........fccccccfffcc55ff........
........ffcccfffccc555cff.......
.........fffffccc555ccccff......
............fcc5555ccccccff.....
..........ff55555cccccccccf.....
.........f5555ccccccccccccff....
........ffcccccccccccccccccf....
........fccccccccccccccccccf....
........ffffffffffffffffffff....
`, img`
.........ffffffffffffff.........
........fccccccccccccccf........
........8888888888888888........
........2222222222222222........
........88888ff888888888........
........fcccfccfcccccccf........
........ffccfccfcccccccf........
.........fccfccfcccccccf........
..........fcfccfcccccccf........
..........fcfccfcccccccf........
..........fcfccfcccccccf........
..........fcfccfcccccccf........
..........fcfccfcccccccf........
..........fcfccfcccccccf........
.........fcccffccccccccf........
........fccccccccccccccf........
........fccccccccccccccf........
.........ffccccccccccccf........
..........fccccccccccccf........
..........fccccccccccccf........
..........ffcccccccccccf........
..........fccccccccccccf........
...........fccccccccccf.........
...........fffcccffcccff........
.............ffffcc5555ff.......
...........fffccc5555cccff......
..........ff5555555ccccccff.....
.........f55555cccccccccccf.....
........ffccccccccccccccccff....
........fccccccccccccccccccf....
........fccccccccccccccccccf....
........ffffffffffffffffffff....
`, img`
.........ffffffffffffff.........
........fccccccccccccccf........
........8888888888888888........
........2222222222222222........
......ff8888888888888888ff......
......fcfccccccccccccccfcf......
......fcfccccccccccccccfcf......
......fcfccccccccccccccfcf......
......fcfccccccccccccccfcf......
......fcfccccccccccccccfcf......
......fcfccccccccccccccfcf......
......fcfccccccccccccccfcf......
......fcfccccccccccccccfcf......
......fcfccccccccccccccfcf......
......fffccccccccccccccfff......
........fccccccccccccccf........
........fccccccccccccccf........
........fccccccccccccccf........
........fccccccccccccccf........
........fccccccccccccccf........
.........fccccccccccccf.........
..........fccccccccccf..........
...........fccccccccf...........
.........ffccccccccccff.........
.......ff555cccccccc555ff.......
......fccc555555555555cccf......
......fccccccccccccccccccf......
.....fccccccccccccccccccccf.....
.....fccccccccccccccccccccf.....
....fccccccccccccccccccccccf....
....fccccccccccccccccccccccf....
....ffffffffffffffffffffffff....
`, img`
.........ffffffffffffff.........
........fccccccccccccccf........
........8888888888888888........
........2222222222222222........
........888888888ff88888........
........fcccccccfccfcccf........
........fcccccccfccfccff........
........fcccccccfccfccf.........
........fcccccccfccfcf..........
........fcccccccfccfcf..........
........fcccccccfccfcf..........
........fcccccccfccfcf..........
........fcccccccfccfcf..........
........fcccccccfccfcf..........
........fccccccccffcccf.........
........fccccccccccccccf........
........fccccccccccccccf........
........fccccccccccccff.........
........fccccccccccccf..........
........fccccccccccccf..........
........fcccccccccccff..........
........fccccccccccccf..........
.........fccccccccccf...........
........ffcccffcccfff...........
.......ff5555ccffff.............
......ffccc5555cccfff...........
.....ffcccccc5555555ff..........
.....fccccccccccc55555f.........
....ffccccccccccccccccff........
....fccccccccccccccccccf........
....fccccccccccccccccccf........
....ffffffffffffffffffff........
`, img`
.........ffffffffffffff.........
........fccccccccccccccf........
........8888888888888888........
........2222222222222222........
........f888888ff8888888........
........fcccccfccfcccccf........
........fcccccfccfcccccf........
........fcccccfccfccccf.........
........fcccccfccfcccf..........
........fcccccfccfcccf..........
........fcccccfccfcccff.........
........fcccccfccfccccf.........
........fcccccfccfccccff........
........fcccccfccfcccccf........
........fccccccffccccccff.......
........fccccccccccccccccf......
........fccccccccccccfcccf......
........fcccccccccccccfff.......
........ffccccccccccccf.........
.........ffcccccccccccff........
..........ffcccccccccccf........
...........ffccccccccfff........
.........ffffffccccccccf........
........ff55ccfffccccccf........
.......ffc555cccfffcccff........
......ffcccc555cccfffff.........
.....ffcccccc5555ccf............
.....fccccccccc55555ff..........
....ffcccccccccccc5555f.........
....fcccccccccccccccccff........
....fccccccccccccccccccf........
....ffffffffffffffffffff........
`, img`
.........ffffffffffffff.........
........fccccccccccccccf........
........8888888888888888........
........2222222222222222........
........888ff88888888888........
........fcfccfcccccccccf........
........fcfccfcfffffffff........
........fcfccfcbbbbbbbf.........
........fcfccfcddddddf..........
........fcfccfcccccccf..........
........fcfccfcccccccf..........
........fcfccfcccccccf..........
........fcfccfcccccccf..........
........fcfccfcccccccff.........
........fccffcccccfccccf........
........fcccccccccfccccf........
........fcccccccccfffff.........
........fcccccccccccf...........
........fccccccccccccf..........
........fccccccccccccf..........
........ffccccccccffff..........
.........ffccccccccccf..........
.........ffffccccccccf..........
........ff5ccffcccccff..........
.......ff555cccffffff...........
......ffccc555cccccf............
.....ffccccc55555ccfff..........
.....fcccccccc5555555ff.........
....ffccccccccccccc555ff........
....fccccccccccccccccccff.......
....fcccccccccccccccccccf.......
....fffffffffffffffffffff.......
`];
        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Auto-generated code. Do not edit.
