def TitleScreen():
    effects.confetti.start_screen_effect()
    game.splash("WELCOME TO", "PARTY GALAXY")
    game.show_long_text("CONTROLS: W,A,S,D/ARROWS - DIRECRIONS, Z/SPACE - SHOOT",
        DialogLayout.BOTTOM)

def on_a_pressed():
    global projectile
    projectile = sprites.create_projectile_from_sprite(assets.image("""
        myImage0
    """), ship, 0, -140)
    projectile.start_effect(effects.trail, 2000)
    animation.run_image_animation(projectile,
        [img("""
                . . . . . . . 2 2 2 . . . . . . 
                        . . . . . . . 2 4 2 . . . . . . 
                        . . . . . . 2 2 4 2 2 . . . . . 
                        . . . . . . 2 4 4 4 2 . . . . . 
                        . . . . . 2 2 4 5 4 2 2 . . . . 
                        . . . . . 2 4 4 5 4 4 2 . . . . 
                        . . . . . 2 4 5 5 5 4 2 . . . . 
                        . . . . . 2 4 5 1 5 4 2 . . . . 
                        . . . . . 2 4 5 1 5 4 2 . . . . 
                        . . . . . 2 4 5 5 5 4 2 . . . . 
                        . . . . . 2 4 4 5 4 4 2 . . . . 
                        . . . . . 2 2 4 5 4 2 2 . . . . 
                        . . . . . . 2 4 4 4 2 . . . . . 
                        . . . . . . 2 2 4 2 2 . . . . . 
                        . . . . . . . 2 4 2 . . . . . . 
                        . . . . . . . 2 2 2 . . . . . .
            """),
            img("""
                . . . . . . . 4 4 4 . . . . . . 
                        . . . . . . . 4 5 4 . . . . . . 
                        . . . . . . 4 4 5 4 4 . . . . . 
                        . . . . . . 4 5 5 5 4 . . . . . 
                        . . . . . 4 4 5 1 5 4 4 . . . . 
                        . . . . . 4 5 5 1 5 5 4 . . . . 
                        . . . . . 4 5 1 1 1 5 4 . . . . 
                        . . . . . 4 5 1 2 1 5 4 . . . . 
                        . . . . . 4 5 1 2 1 5 4 . . . . 
                        . . . . . 4 5 1 1 1 5 4 . . . . 
                        . . . . . 4 5 5 1 5 5 4 . . . . 
                        . . . . . 4 4 5 1 5 4 4 . . . . 
                        . . . . . . 4 5 5 5 4 . . . . . 
                        . . . . . . 4 4 5 4 4 . . . . . 
                        . . . . . . . 4 5 4 . . . . . . 
                        . . . . . . . 4 4 4 . . . . . .
            """),
            img("""
                . . . . . . . 5 5 5 . . . . . . 
                        . . . . . . . 5 1 5 . . . . . . 
                        . . . . . . 5 5 1 5 5 . . . . . 
                        . . . . . . 5 1 1 1 5 . . . . . 
                        . . . . . 5 5 1 2 1 5 5 . . . . 
                        . . . . . 5 1 1 2 1 1 5 . . . . 
                        . . . . . 5 1 2 2 2 1 5 . . . . 
                        . . . . . 5 1 2 4 2 1 5 . . . . 
                        . . . . . 5 1 2 4 2 1 5 . . . . 
                        . . . . . 5 1 2 4 2 1 5 . . . . 
                        . . . . . 5 1 2 2 2 1 5 . . . . 
                        . . . . . 5 1 1 2 1 1 5 . . . . 
                        . . . . . 5 5 1 1 1 5 5 . . . . 
                        . . . . . . 5 5 1 5 5 . . . . . 
                        . . . . . . . 5 1 5 . . . . . . 
                        . . . . . . . 5 5 5 . . . . . .
            """),
            img("""
                . . . . . . . . 1 . . . . . . . 
                        . . . . . . . 1 2 1 . . . . . . 
                        . . . . . . . 1 2 1 . . . . . . 
                        . . . . . . 1 2 2 2 1 . . . . . 
                        . . . . . . 1 2 4 2 1 . . . . . 
                        . . . . . 1 2 2 4 2 2 1 . . . . 
                        . . . . . 1 2 4 4 4 2 1 . . . . 
                        . . . . . 1 2 4 5 4 2 1 . . . . 
                        . . . . . 1 2 4 5 4 2 1 . . . . 
                        . . . . . 1 2 4 4 4 2 1 . . . . 
                        . . . . . 1 2 2 4 2 2 1 . . . . 
                        . . . . . 1 1 2 4 2 1 1 . . . . 
                        . . . . . 1 1 2 2 2 1 1 . . . . 
                        . . . . . . 1 1 2 1 1 . . . . . 
                        . . . . . . . 1 2 1 . . . . . . 
                        . . . . . . . 1 1 1 . . . . . .
            """)],
        100,
        True)
controller.A.on_event(ControllerButtonEvent.PRESSED, on_a_pressed)

def on_on_overlap(sprite, otherSprite):
    sprite.destroy()
    otherSprite.destroy(effects.disintegrate)
    info.change_score_by(1)
sprites.on_overlap(SpriteKind.projectile, SpriteKind.enemy, on_on_overlap)

def on_on_overlap2(sprite2, otherSprite2):
    scene.camera_shake(8, 1500)
    otherSprite2.destroy(effects.halo)
    sprite2.start_effect(effects.fire, 200)
    info.change_life_by(-1)
sprites.on_overlap(SpriteKind.player, SpriteKind.enemy, on_on_overlap2)

projectile: Sprite = None
ship: Sprite = None
TitleScreen()
asteroids = [assets.image("""
        myImage4
    """),
    assets.image("""
        myImage3
    """),
    assets.image("""
        myImage2
    """),
    assets.image("""
        myImage5
    """),
    img("""
        . . . . . . . . . . . . . . . . 
            . . . . . . f f f f . . . . . . 
            . . . . . f 7 1 3 3 f . . . . . 
            . . . . f 7 7 1 3 3 3 f . . . . 
            . . . . f 7 7 1 3 3 3 f . . . . 
            . . . f 7 7 1 1 3 3 1 1 f . . . 
            . . . f 7 1 1 1 1 1 1 2 f . . . 
            . . f 7 1 1 5 1 1 1 2 2 2 f . . 
            . . f 1 1 5 5 5 1 2 2 2 2 f . . 
            . . f 1 1 1 5 1 1 2 2 2 2 f . . 
            . . f 4 4 1 1 1 1 1 2 2 2 f . . 
            . . f 4 4 4 1 1 1 1 1 2 2 f . . 
            . . f 4 4 4 4 1 1 a 1 1 1 f . . 
            . . . f 4 4 4 1 a a a 1 f . . . 
            . . . . f f 4 1 a a f f . . . . 
            . . . . . . f f f f . . . . . .
    """)]
ship = sprites.create(assets.image("""
    myImage
"""), SpriteKind.player)
animation.run_image_animation(ship,
    [img("""
            .........ffffffffffffff.........
                ........fccccccccccccccf........
                ........8888888888888888........
                ........2222222222222222........
                ......ff8888888888888888ff......
                ......fcfccccccccccccccfcf......
                ......fcfcffffffffffffcfcf......
                ......fcfcbbbbbbbbbbbbcfcf......
                ......fcfcddddddddddddcfcf......
                ......fcfcccccfccfcccccfcf......
                ......fcfcccccfccfcccccfcf......
                ......fcfcccccfccfcccccfcf......
                ......fcfcccccfccfcccccfcf......
                ......fcfcccccfccfcccccfcf......
                ......fffccccffccffccccfff......
                ........fcccfcfccfcfcccf........
                ........fcccfccccccfcccf........
                ........fccccfccccfccccf........
                ........fcccccffffcccccf........
                ........fccccccccccccccf........
                .........fccccccccccccf.........
                ..........fcccffffcccf..........
                ...........fccccccccf...........
                .........ffcfccccccfcff.........
                .......ff55ccffffffcc55ff.......
                ......fccc55cccccccc55cccf......
                ......fcccc55cccccc55ccccf......
                .....fcccccc555cc555ccccccf.....
                .....fcccccccc5555ccccccccf.....
                ....fccccccccccccccccccccccf....
                ....fccccccccccccccccccccccf....
                ....ffffffffffffffffffffffff....
        """),
        img("""
            .........ffffffffffffff.........
                ........fccccccccccccccf........
                ........8888888888888888........
                ........2222222222222222........
                ........88888888888ff888........
                ........fcccccccccfccfcf........
                ........fffffffffcfccfcf........
                .........fbbbbbbbcfccfcf........
                ..........fddddddcfccfcf........
                ..........fcccccccfccfcf........
                ..........fcccccccfccfcf........
                ..........fcccccccfccfcf........
                ..........fcccccccfccfcf........
                .........ffcccccccfccfcf........
                ........fccccfcccccffccf........
                ........fccccfcccccccccf........
                .........fffffcccccccccf........
                ...........fcccccccccccf........
                ..........fccccccccccccf........
                ..........fccccccccccccf........
                ..........ffffccccccccff........
                ..........fccccccccccff.........
                ..........fccccccccffff.........
                ..........ffcccccffcc5ff........
                ...........ffffffccc555ff.......
                ............fccccc555cccff......
                ..........fffcc55555cccccff.....
                .........ff5555555ccccccccf.....
                ........ff555cccccccccccccff....
                .......ffccccccccccccccccccf....
                .......fcccccccccccccccccccf....
                .......fffffffffffffffffffff....
        """),
        img("""
            .........ffffffffffffff.........
                ........fccccccccccccccf........
                ........8888888888888888........
                ........2222222222222222........
                ........8888888ff888888f........
                ........fcccccfccfcccccf........
                ........fcccccfccfcccccf........
                .........fccccfccfcccccf........
                ..........fcccfccfcccccf........
                ..........fcccfccfcccccf........
                .........ffcccfccfcccccf........
                .........fccccfccfcccccf........
                ........ffccccfccfcccccf........
                ........fcccccfccfcccccf........
                .......ffccccccffccccccf........
                ......fccccccccccccccccf........
                ......fcccfccccccccccccf........
                .......fffcccccccccccccf........
                .........fccccccccccccff........
                ........ffcccccccccccff.........
                ........fcccccccccccff..........
                ........fffccccccccff...........
                ........fccccccccffffff.........
                ........fccccccfffcc55ff........
                ........ffcccfffccc555cff.......
                .........fffffccc555ccccff......
                ............fcc5555ccccccff.....
                ..........ff55555cccccccccf.....
                .........f5555ccccccccccccff....
                ........ffcccccccccccccccccf....
                ........fccccccccccccccccccf....
                ........ffffffffffffffffffff....
        """),
        img("""
            .........ffffffffffffff.........
                ........fccccccccccccccf........
                ........8888888888888888........
                ........2222222222222222........
                ........88888ff888888888........
                ........fcccfccfcccccccf........
                ........ffccfccfcccccccf........
                .........fccfccfcccccccf........
                ..........fcfccfcccccccf........
                ..........fcfccfcccccccf........
                ..........fcfccfcccccccf........
                ..........fcfccfcccccccf........
                ..........fcfccfcccccccf........
                ..........fcfccfcccccccf........
                .........fcccffccccccccf........
                ........fccccccccccccccf........
                ........fccccccccccccccf........
                .........ffccccccccccccf........
                ..........fccccccccccccf........
                ..........fccccccccccccf........
                ..........ffcccccccccccf........
                ..........fccccccccccccf........
                ...........fccccccccccf.........
                ...........fffcccffcccff........
                .............ffffcc5555ff.......
                ...........fffccc5555cccff......
                ..........ff5555555ccccccff.....
                .........f55555cccccccccccf.....
                ........ffccccccccccccccccff....
                ........fccccccccccccccccccf....
                ........fccccccccccccccccccf....
                ........ffffffffffffffffffff....
        """),
        img("""
            .........ffffffffffffff.........
                ........fccccccccccccccf........
                ........8888888888888888........
                ........2222222222222222........
                ......ff8888888888888888ff......
                ......fcfccccccccccccccfcf......
                ......fcfccccccccccccccfcf......
                ......fcfccccccccccccccfcf......
                ......fcfccccccccccccccfcf......
                ......fcfccccccccccccccfcf......
                ......fcfccccccccccccccfcf......
                ......fcfccccccccccccccfcf......
                ......fcfccccccccccccccfcf......
                ......fcfccccccccccccccfcf......
                ......fffccccccccccccccfff......
                ........fccccccccccccccf........
                ........fccccccccccccccf........
                ........fccccccccccccccf........
                ........fccccccccccccccf........
                ........fccccccccccccccf........
                .........fccccccccccccf.........
                ..........fccccccccccf..........
                ...........fccccccccf...........
                .........ffccccccccccff.........
                .......ff555cccccccc555ff.......
                ......fccc555555555555cccf......
                ......fccccccccccccccccccf......
                .....fccccccccccccccccccccf.....
                .....fccccccccccccccccccccf.....
                ....fccccccccccccccccccccccf....
                ....fccccccccccccccccccccccf....
                ....ffffffffffffffffffffffff....
        """),
        img("""
            .........ffffffffffffff.........
                ........fccccccccccccccf........
                ........8888888888888888........
                ........2222222222222222........
                ........888888888ff88888........
                ........fcccccccfccfcccf........
                ........fcccccccfccfccff........
                ........fcccccccfccfccf.........
                ........fcccccccfccfcf..........
                ........fcccccccfccfcf..........
                ........fcccccccfccfcf..........
                ........fcccccccfccfcf..........
                ........fcccccccfccfcf..........
                ........fcccccccfccfcf..........
                ........fccccccccffcccf.........
                ........fccccccccccccccf........
                ........fccccccccccccccf........
                ........fccccccccccccff.........
                ........fccccccccccccf..........
                ........fccccccccccccf..........
                ........fcccccccccccff..........
                ........fccccccccccccf..........
                .........fccccccccccf...........
                ........ffcccffcccfff...........
                .......ff5555ccffff.............
                ......ffccc5555cccfff...........
                .....ffcccccc5555555ff..........
                .....fccccccccccc55555f.........
                ....ffccccccccccccccccff........
                ....fccccccccccccccccccf........
                ....fccccccccccccccccccf........
                ....ffffffffffffffffffff........
        """),
        img("""
            .........ffffffffffffff.........
                ........fccccccccccccccf........
                ........8888888888888888........
                ........2222222222222222........
                ........f888888ff8888888........
                ........fcccccfccfcccccf........
                ........fcccccfccfcccccf........
                ........fcccccfccfccccf.........
                ........fcccccfccfcccf..........
                ........fcccccfccfcccf..........
                ........fcccccfccfcccff.........
                ........fcccccfccfccccf.........
                ........fcccccfccfccccff........
                ........fcccccfccfcccccf........
                ........fccccccffccccccff.......
                ........fccccccccccccccccf......
                ........fccccccccccccfcccf......
                ........fcccccccccccccfff.......
                ........ffccccccccccccf.........
                .........ffcccccccccccff........
                ..........ffcccccccccccf........
                ...........ffccccccccfff........
                .........ffffffccccccccf........
                ........ff55ccfffccccccf........
                .......ffc555cccfffcccff........
                ......ffcccc555cccfffff.........
                .....ffcccccc5555ccf............
                .....fccccccccc55555ff..........
                ....ffcccccccccccc5555f.........
                ....fcccccccccccccccccff........
                ....fccccccccccccccccccf........
                ....ffffffffffffffffffff........
        """),
        img("""
            .........ffffffffffffff.........
                ........fccccccccccccccf........
                ........8888888888888888........
                ........2222222222222222........
                ........888ff88888888888........
                ........fcfccfcccccccccf........
                ........fcfccfcfffffffff........
                ........fcfccfcbbbbbbbf.........
                ........fcfccfcddddddf..........
                ........fcfccfcccccccf..........
                ........fcfccfcccccccf..........
                ........fcfccfcccccccf..........
                ........fcfccfcccccccf..........
                ........fcfccfcccccccff.........
                ........fccffcccccfccccf........
                ........fcccccccccfccccf........
                ........fcccccccccfffff.........
                ........fcccccccccccf...........
                ........fccccccccccccf..........
                ........fccccccccccccf..........
                ........ffccccccccffff..........
                .........ffccccccccccf..........
                .........ffffccccccccf..........
                ........ff5ccffcccccff..........
                .......ff555cccffffff...........
                ......ffccc555cccccf............
                .....ffccccc55555ccfff..........
                .....fcccccccc5555555ff.........
                ....ffccccccccccccc555ff........
                ....fccccccccccccccccccff.......
                ....fcccccccccccccccccccf.......
                ....fffffffffffffffffffff.......
        """)],
    100,
    True)
ship.set_stay_in_screen(True)
ship.bottom = 120
controller.move_sprite(ship, 100, 100)
info.set_life(3)
effects.blizzard.start_screen_effect()

def on_update_interval():
    global projectile
    projectile = sprites.create_projectile_from_side(asteroids[randint(0, len(asteroids) - 1)], 0, 75)
    projectile.set_kind(SpriteKind.enemy)
    projectile.x = randint(10, 150)
game.on_update_interval(20, on_update_interval)
